%\VignetteIndexEntry{tilingArray - demo segmentation}
%\VignetteDepends{tilingArray}
%\VignetteKeywords{segmentation}
%\VignettePackage{tilingArray}

\documentclass[11pt]{article}
\usepackage{geometry}\usepackage{color}
\definecolor{darkblue}{rgb}{0.0,0.0,0.75}
\usepackage[%
baseurl={http://www.bioconductor.org},%
pdftitle={Segmentation demo},%
pdfauthor={Wolfgang Huber},%
pdfsubject={tilingArray},%
pdfkeywords={Bioconductor},%
pagebackref,bookmarks,colorlinks,linkcolor=darkblue,citecolor=darkblue,%
pagecolor=darkblue,raiselinks,plainpages,pdftex]{hyperref}

%------------------------------------------------------------
% newcommand
%------------------------------------------------------------
\newcommand{\Robject}[1]{\texttt{#1}}
\newcommand{\Rpackage}[1]{\textit{#1}}
\newcommand{\Rclass}[1]{\textit{#1}}
\newcommand{\Rfunction}[1]{{\small\texttt{#1}}}

\newcommand{\myincfig}[3]{%
  \begin{figure}[htbp]
    \begin{center}
      \includegraphics[width=#2]{#1}
      \caption{\label{#1}#3}
    \end{center}
  \end{figure}
}

\begin{document}

%------------------------------------------------------------
\title{Segmentation demo}
%------------------------------------------------------------
\author{Wolfgang Huber}
\maketitle
\tableofcontents

\section{Introduction}
This script presents a demo of the segmentation function
on the \Rpackage{davidTiling} data.

<<setup, results=hide>>=
options(error=recover, warn=0)
graphics.off()

library("tilingArray")
library("davidTiling")
if(!exists("davidTiling"))
  data("davidTiling")
if(!exists("probeAnno"))
  data("probeAnno")
@ 

%--------------------------------------------------
\section{Normalization}
%--------------------------------------------------
Please see the vignette \textit{Assessing signal/noise ratio before
and after normalization} (\texttt{assessNorm.Rnw}) for explanation.
<<normalization>>=
xn = cache("xn", {
  nc = as.integer(2560)
  PMind = rep(seq(as.integer(1), nc-as.integer(3), by=as.integer(2)), each=nc)*nc + (1:nc)
  MMind = PMind + nc

  ispm = rep(FALSE, nc*nc)
  ispm[PMind] = TRUE
  isbg = (probeAnno$probeReverse$no_feature=="no" &
          probeAnno$probeDirect$no_feature=="no" &
          ispm)
  isRNA = davidTiling$nucleicAcid %in% c("poly(A) RNA","total RNA")
  isDNA = davidTiling$nucleicAcid %in% "genomic DNA"
  stopifnot(sum(isRNA)==5, sum(isDNA)==3)
  normalizeByReference(davidTiling[,isRNA], davidTiling[,isDNA], 
                       pm=PMind, background=isbg)
})
pData(xn)[, 2, drop=FALSE]
@ 


%--------------------------------------------------
\section{Segmentation}
%--------------------------------------------------

\subsection{Selecting the probes in along-chromosome order}
Extract for all probes that map to the "+" strand of chromosome 1  their
start and end coordinate, and their index in the exprs(davidTiling)
data matrix.  Sort them by midpoint.

<<prbs>>=
chrstrd = "1.+"
what = c("start", "end", "index", "unique")
prbs = do.call("data.frame",
  mget(paste(chrstrd, what, sep="."), probeAnno))
colnames(prbs) = what
prbs$mid = (prbs$start+prbs$end)/2
prbs = prbs[order(prbs$mid), ]
@ 

We throw out the missing (\Robject{NA}) values:
<<throwOutNA>>=
numna = rowSums(is.na(exprs(xn)[ prbs$ind, ]))
stopifnot(all(numna %in% c(0, ncol(xn))))
prbs = prbs[numna==0,]
@ 

%--------------------------------------------------
\subsubsection{Avoid oversampling}
<<sampleStep>>=
sprb = prbs[ sampleStep(prbs$mid, step=7), ]
@ 

<<histprobs, fig=TRUE, include=FALSE, width=6, height=7>>=
par(mfrow=c(3,1))
hist(prbs$mid, col="mistyrose", 100, main="(a)")
barplot(table(diff(prbs$mid)), main="(b)")
barplot(table(diff(sprb$mid)), main="(c)")
@ 
%
\myincfig{segmentation-histprobs}{0.7\textwidth}{% 
(a):
Histogram of probe midpoints along the chromosome.  There are some
probe dense regions in particular around 160,000.  The sequence of
that region is repeated multiple times in the genome, and due to the
chip design, there are also a lot of probes (more than necessary) for that region.
(b): histogram of differences between probe midpoints (\Robject{prbs\$mid}).
The intention of the chip design was to have a regular spacing of 8 bases.
In some cases, the spacing is wider, probably due to updates in the 
genome sequence between when the chip was designed and 
when probes were re-aligned. In  many cases, it is tighter with multiple 
probes for the same target sequence, or only 1 or 2 bases offset. This occurs 
in the regions of duplicated sequence.
(c): histogram of differences between probe midpoints after sampling
(\Robject{sprb\$mid})
}

%--------------------------------------------------
\subsection{Call the segmentation algorithm}
The segmentation algorithm needs two parameters, 
\Robject{maxseg}, the maximum number of segments
that the algorithm is going to consider, and \Robject{maxk}, the
maximum length per segment (in data points) of individual segments.
The algorithm will calculate all optimal segmentations with $1, 2,
\ldots, \mbox{maxseg}$ segments. The choice that we make here corresponds
to an \emph{average} length per segment of 1500 bases.
Our choice of the parameter \Robject{maxk} corresponds to a maximum 
segment length of about $7.5 \times 3,000 = 22,500$ bases.
<<maxseg, print=TRUE>>=
maxseg = round(sprb$end[nrow(sprb)]/1500)
@ 
%
<<segment>>=
seg = cache("seg", {
  y = exprs(xn)[sprb$ind, xn$nucleicAcid=="poly(A) RNA", drop=FALSE]
  seg = segment(y, maxseg=maxseg, maxk=3000)
  seg@x = sprb$mid
  seg@flag = sprb$unique
})
@ 
%
We also add additional information to the object that wasn't used for
the actual segmentation, but will be useful for the visualization:
\code{seg@x}, the $x$-coordinates of the probes, and \code{seg@flag},
uniqueness status of the probes (0 iff the probe has exactly one match
in the genome).

Having to access the \code{x} and \code{flag} slots directly, in the
code above, is of course a bit unelegant; accessor functions will be
written in subsequent versions of the package.

%--------------------------------------------------
\subsection{Calculate confidence intervals}

<<confint>>=
segc = cache("segc",
  confint(seg, parm=maxseg)
)
@ 

<<plotseg, fig=TRUE, include=FALSE, width=8, height=4, eps=FALSE>>=
source("/homes/huber/madman/Rpacks/tilingArray/R/methods-segmentation.R")
plot(segc, maxseg, pch=".", xlim=c(0, 40000))
@ 
\myincfig{segmentation-plotseg}{\textwidth}{% 
Segmentation with confidence intervals.
}

<<plotAlongChrom, fig=TRUE, include=FALSE, width=8, height=7>>=
data("gff")
source("/homes/huber/madman/Rpacks/tilingArray/R/plotAlongChrom.R")
plotAlongChrom(segc, chr=1, coord = 1000*c(76.2, 92.8),
               gff = gff)

@ 

\end{document}





          
